spring.application.name=product_availability_service

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/product_availability}
spring.datasource.username=${DB_USERNAME:product_app}
spring.datasource.password=${DB_PASSWORD:product_app}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}

spring.cache.type=redis
spring.cache.cache-names=products
spring.cache.redis.time-to-live=5m